name: droidian rootfs-builder

on:
  workflow_dispatch:
  push:
    branches:
      - trixie
  schedule:
    - cron: "59 23 * * *"

jobs:
  once:
    runs-on: ubuntu-22.04
    name: Generate matrix
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate matrix
        id: gen-matrix
        run: |
          JOBS="$(./generate_device_recipe.py --matrix)"
          echo "matrix=${JOBS}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs: once

    strategy:
      fail-fast: true
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: ${{ matrix.config.job_name }}

    steps:
      - name: Get current date
        run: echo "current_date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set suffix
        run: echo "release_suffix=_${{ env.current_date }}" >> $GITHUB_ENV

      - name: Set nightly version
        if: startsWith(github.ref, 'refs/tags/droidian') != true
        run: echo "DROIDIAN_VERSION=nightly" >> $GITHUB_ENV

      - name: Set version
        if: startsWith(github.ref, 'refs/tags/droidian') == true
        run: echo "DROIDIAN_VERSION=$(echo ${{ github.ref }} | rev | cut -d'/' -f1 | rev)" >> $GITHUB_ENV

      - name: Set identifier
        run: echo "DROIDIAN_IDENTIFIER=${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Create build dir
        run: mkdir -p /tmp/buildd-results

      - name: Pull container
        run: docker pull quay.io/droidian/rootfs-builder:trixie-amd64

      - name: Start Container
        run: |
             docker run --detach --privileged \
             --name droidian-builder \
             -v /tmp/buildd-results:/buildd/out \
             -v /dev:/host-dev \
             -v /sys/fs/cgroup:/sys/fs/cgroup \
             -v ${PWD}:/buildd/sources \
             --security-opt seccomp:unconfined \
             quay.io/droidian/rootfs-builder:trixie-amd64 \
             sleep infinity

      - name: Build rootfs
        run: |
             docker exec droidian-builder /bin/sh -c 'cd /buildd/sources; DROIDIAN_VERSION="${{ env.DROIDIAN_VERSION }}" ./generate_device_recipe.py ${{ matrix.config.product }} ${{ matrix.config.arch }} ${{ matrix.config.edition }} ${{ matrix.config.variant }} ${{ matrix.config.apilevel }} && debos --disable-fakemachine generated/droidian.yaml'

  prepare:
    runs-on: ubuntu-22.04
    name: Prepare release
    needs: build
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Free up some storage
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Delete old nightly release
        if: startsWith(github.ref, 'refs/tags/droidian') != true
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old droidian-installer release
        if: startsWith(github.ref, 'refs/tags/droidian') != true
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: droidian-installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag snapshot
        if: startsWith(github.ref, 'refs/tags/droidian') != true
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: droidian-out

      - name: Create SHA256SUMS
        run: |
          cd droidian-out
          for x in droidian-out-*; do
            cd $x
            sha256sum * >> ../SHA256SUMS
            cd ..
          done

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: droidian-out/SHA256SUMS
          tag_name: ${{ startsWith(github.ref, 'refs/tags/droidian') && github.ref || 'nightly' }}
          draft: ${{ startsWith(github.ref, 'refs/tags/droidian') }}
          prerelease: false

  publish:
    runs-on: ubuntu-22.04
    needs: [once, prepare]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: Publish ${{ matrix.config.job_name }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: droidian-out-${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}
          path: droidian-out

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: droidian-out/*
          tag_name: ${{ startsWith(github.ref, 'refs/tags/droidian') && github.ref || 'nightly' }}
          draft: ${{ startsWith(github.ref, 'refs/tags/droidian') }}
          prerelease: false

  publish_installer:
    runs-on: ubuntu-22.04
    needs: [once, prepare, publish]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: Publish installer ${{ matrix.config.job_name }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: droidian-out-${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}
          path: droidian-installer

      - name: Prepare installer zip
        run: |
          mv droidian-installer/droidian-UNOFFICIAL*.zip droidian-installer/droidian-UNOFFICIAL_${{ matrix.config.product }}-${{ matrix.config.arch }}-${{ matrix.config.edition }}-${{ matrix.config.variant }}-${{ matrix.config.apilevel }}.zip

      - name: Upload installer
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: droidian-installer
          file: droidian-installer/*.zip
          file_glob: true
          overwrite: true
          prerelease: true
